import type { Metadata } from "next";
import "@/styles/globals.css";
import Header from "@/ui/Header";
import { Inter } from 'next/font/google'
import { UserProvider } from "@/context/UserContext"
import Footer from "@/ui/Footer";

export const metadata: Metadata = {
  title: "Abricot",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ['latin'] })

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className}>
      <body>
        <UserProvider>
            <Header />
            {children}
            <Footer />
        </UserProvider>
      </body>
    </html>
  );
}
